## Environment POSTGRES
version: '3'
services:
  environment:
    container_name: environment-postgres
    image: environment-postgres
    hostname: environment-postgres
    labels:
      description: environment-postgres
      org.opencontainers.image.name: environment-postgres
      org.opencontainers.image.authors: Lucas Costa
      org.opencontainers.image.hostname: environment-postgres
      com.docker.volume.name: environment-postgres
      com.docker.network.bridge.name: environment-postgres

    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
      - local-volume:/var/lib/postgresql/data/*
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: development
      POSTGRES_USER: development
      POSTGRES_PASSWORD: Alterar123
    networks:
      local-network:
    restart: always
    ports:
      - "5432:5432" # host:container
volumes:
  local-volume:
    name: environment-postgres
networks:
  local-network:
    name: environment-postgres
    driver: bridge
