## Environment ELASTIC SEARCH
version: '3'
services:
  environment:
    container_name: environment-elasticsearch
    image: environment-elasticsearch
    hostname: environment-elasticsearch
    labels:
      description: environment-elasticsearch
      org.opencontainers.image.name: environment-elasticsearch
      org.opencontainers.image.authors: Lucas Costa
      org.opencontainers.image.hostname: environment-elasticsearch
      com.docker.volume.name: environment-elasticsearch
      com.docker.network.bridge.name: environment-elasticsearch
    build: 
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/share/elasticsearch/data
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - local-volume:/usr/share/elasticsearch/data/*
    env_file:
      - ./.env
    environment:
      - node.name=environment-es01
      - cluster.name=evironment-es
      - cluster.initial_master_nodes=environment-es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      local-network:
    restart: always
    ports:
      - 9200:9200 # host:container
volumes:
  local-volume:
    name: environment-elasticsearch
networks:
  local-network:
    name: environment-elasticsearch
    driver: bridge
