## Environment NODE
version: "3"
services:
  environment:
    container_name: environment-node
    image: environment-node
    hostname: environment-node
    labels:
      description: environment-node
      org.opencontainers.image.name: environment-node
      org.opencontainers.image.authors: Lucas Costa
      org.opencontainers.image.hostname: environment-node
      com.docker.volume.name: environment-node
      com.docker.network.bridge.name: environment-node
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/usr/environment-node
    env_file:
      - ./.env
    environment:
      NODE_ENV: development
    command: npm run dev
    networks:
      - local-network
    restart: always
    ports:
      - 3000:3000
volumes:
  local-volume:
    name: environment-node
networks:
  local-network:
    name: environment-node
    driver: bridge
