## Environment NODE
version: "3.8"

services:

  environment-node:
    container_name: environment-node
    image: environment-node
    labels:
      environment-node: "environment-node"
    build: .
    volumes:
      - .:/usr/environment-node
    env_file:
      - ./.env
    environment:
      NODE_ENV: development
    command: npm run development
    networks:
      - environment-node
    restart: always
    ports:
      - 3000:3000

volumes:
  environment-node:
    name: environment-node
networks:
  environment-node:
    name: environment-node
    driver: bridge
