## Environment MYSQL
version: '3.8'

services:

  ##################### MYSQL #####################
  environment-mysql:
    container_name: environment-mysql
    build: 
      context: .
      dockerfile: Dockerfile
    labels:
      environment-mysql: "environment-mysql"
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      environment-mysql:
    restart: always
    ports:
      - 3306:3306 # host:container

##################### VOLUMES #####################
volumes:
  environment-mysql:
    name: environment-mysql

##################### NETWORKS #####################
networks:
  environment-mysql:
    name: environment-mysql
    driver: bridge
