# Use root/example as user/password credentials
version: '3.1'

services:

  environment-mysql:
    container_name: environment-mysql
    hostname: environment-mysql
    image: mysql
    volumes:
      - ./data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "development"
      MYSQL_USER: "development"
      MYSQL_ROOT_PASSWORD: "Alterar123"
      MYSQL_PASSWORD: "Alterar123"
    
    ports:
      - 3306:3306
