version: "3"
services:
  environment:
    container_name: environment-go
    image: environment-go
    hostname: environment-go
    labels:
      description: environment-go
      org.opencontainers.image.name: environment-go
      org.opencontainers.image.authors: Lucas Costa
      org.opencontainers.image.hostname: environment-go
      com.docker.volume.name: environment-go
      com.docker.network.bridge.name: environment-go
    build: 
      context: ./
      dockerfile: Dockerfile
      target: environment-go
    working_dir: /go/src/github.com/environment-go
    volumes:
      - .:/go/src/github.com/environment-go
    env_file: ".env"
    environment:
      GO_ENV: "development"
    command: bash -c "gin -i run"
    networks:
      - local-network
    restart: always
    ports:
      - 5000:5000
volumes:
  local-volume:
    name: environment-go
networks:
  local-network:
    name: environment-go
    driver: bridge
