## Environment MYSQL
version: '3.8'

services:

  ##################### MYSQL #####################
  environment-mysql:
    container_name: environment-mysql
    image: mysql:5.7
    labels:
      environment-mysql: "environment-mysql"
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: development
      MYSQL_USER: development
      MYSQL_ROOT_PASSWORD: Alterar123
      MYSQL_PASSWORD: Alterar123
    command: --default-authentication-plugin=mysql_native_password
    networks:
      environment-mysql:
    restart: always
    ports:
      - 3307:3306 # host:container

##################### VOLUMES #####################
volumes:
  environment-mysql:
    name: environment-mysql

##################### NETWORKS #####################
networks:
  environment-mysql:
    name: environment-mysql
    driver: bridge
