version: "3.8"
services:
  ##################### GO #####################
  environment-go:
    container_name: environment-go
    labels:
      environment-go: "environment-go"
      name: "environment-go"
    # image: cintosyntax/docker-golang-live-reloading
    build: .
    working_dir: /go/src/github.com/environment-go
    volumes:
      - .:/go/src/github.com/environment-go
    env_file: ".env"
    environment:
      GO_ENV: "development"
    command: bash -c "gin -i run"
    networks:
      - environment-go
    restart: always
    ports:
      - 5000:5000

##################### VOLUMES #####################
volumes:
  environment-go:
    name: environment-go

##################### NETWORK #####################
networks:
  environment-go:
    name: environment-go
    driver: bridge
