version: "3"
services:
  environment:
    image: environment-go
    hostname: environment-go
    container_name: environment-go
    labels:
      description: environment-go
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    working_dir: /go/src
    volumes:
      - .:/go/src
    env_file: 
      - ./.env
    environment:
      GO_ENV: "development"
      GOPORT: ${PORT}
      TZ: ${TIMEZONE}
    command: bash -c "gin -i run"
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}

  production:
    image: production-go
    hostname: production-go
    container_name: production-go
    build: 
      context: ./
      dockerfile: Dockerfile
    command: bash -c "gin -i run"
    environment:  
      GOPORT: 9001
    restart: unless-stopped
    ports:
      - 9001:9001