version: "3.8"
services:
  ##################### GO lang #####################
  environment-go:
    container_name: environment-go
    labels:
      environment-go: "environment-go"
      name: "environment-go"
    build: .
    volumes:
      - .:/usr/environment-go
    env_file:
      - ./.env
    environment:
      GO_ENV: development
    command: air
    networks:
      - environment-go
    restart: always
    ports:
      - 5000:5000

##################### VOLUMES #####################
volumes:
  environment-go:
    name: environment-go

##################### NETWORK #####################
networks:
  environment-go:
    name: environment-go
    driver: bridge
