version: "3"
services:
  environment:
    image: environment-go
    hostname: environment-go
    container_name: environment-go
    labels:
      description: environment-go
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/usr/local/github.com/lucasfrct/environment-go
    env_file: 
      - ./.env
    environment:
      GO_ENV: "development"
      GOPORT: ${PORT}
    command: bash -c "gin -i run"
    networks:
      - local-network
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
volumes:
  local-volume:
networks:
  local-network: