version: "3"
services:
  environment:
    image: environment-go
    hostname: environment-go
    container_name: environment-go
    labels:
      description: environment-go
      com.docker.volume.name: environment-go
      org.opencontainers.image.name: environment-go
      com.docker.network.bridge.name: environment-go
      org.opencontainers.image.authors: Lucas Costa
      org.opencontainers.image.hostname: environment-go
    build: 
      context: ./
      target: environment-go
      dockerfile: Dockerfile
    cpus: 1
    # depends_on:
    #   - environment-mysql
    #   - environment-api
    working_dir: /go/src/github.com/environment-go
    volumes:
      - .:/go/src/github.com/environment-go
      - local-volume:/go/src/github.com/environment-go
    env_file: 
      - ./.env
    environment:
      GO_ENV: "development"
      GOPORT: 9000
    command: bash -c "gin -i run"
    networks:
      - local-network
    restart: always
    ports:
      - 9000:9000
      - 9001:3000 # go gin live reload
volumes:
  local-volume:
    name: environment-go
networks:
  local-network:
    name: environment-go
    driver: bridge