version: "3"
services:
  environment:
    image: environment-go
    hostname: environment-go
    container_name: environment-go
    labels:
      description: environment-go
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - .:/go/src
    env_file: 
      - ./.env
    environment:
      GO_ENV: "development"
      GOPORT: ${PORT}
    command: bash -c "gin -i run"
    # command: bash -c "bee run"
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}