## Environment DYNAMO DB
version: '3'
services:
  environment:
    container_name: environment-dynamodb
    image: environment-dynamodb 
    hostname: environment-dynamodb
    labels:
      description: environment-dynamodb
      org.opencontainers.image.name: environment-dynamodb
      org.opencontainers.image.authors: Lucas Costa
      org.opencontainers.image.hostname: environment-dynamodb
      com.docker.volume.name: environment-dynamodb
      com.docker.network.bridge.name: environment-dynamodb
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./data:/home/dynamodblocal/data
      - local-volume:/home/dynamodblocal/data/*
    env_file:
      - ./.env
    environment:
      DYNAMODB_USER: development
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    networks:
      local-network:
    restart: always
    ports:
      - 8000:8000 # host:container
volumes:
  local-volume:
    name: environment-dynamodb
networks:
  local-network:
    name: environment-dynamodb
    driver: bridge
