version: "3"
services:
  environment:
    image: environment-java
    hostname: environment-java
    container_name: environment-java
    labels:
      description: environment-java
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/environment-java
    env_file:
      - ./.env 
    environment:
      JAVA_ENV: "development"
      PORT: ${PORT}
    command: mvn spring-boot:run
    networks:
      - local-network
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
volumes:
  local-volume:
networks:
  local-network: