## Environment REDIS
version: '3'
services:
  environment:
    container_name: environment-redis
    image: environment-redis
    hostname: environment-redis
    labels:
      description: environment-redis
      org.opencontainers.image.name: environment-redis
      org.opencontainers.image.authors: Lucas Costa
      org.opencontainers.image.hostname: environment-redis
      com.docker.volume.name: environment-redis
      com.docker.network.bridge.name: environment-redis
    build: 
      context: ./
      dockerfile: Dockerfile
    working_dir: /data
    volumes:
      - ./data:/data
      - local-volume:/data/*
    env_file:
      - ./.env
    environment:
      REDIS_PASSWORD: Alterar123
    command: redis-server --save 20 1 --loglevel warning --requirepass Alterar123
    networks:
      local-network:
    restart: always
    ports:
      - 6379:6379 # host:container
volumes:
  local-volume:
    name: environment-redis
networks:
  local-network:
    name: environment-redis
    driver: bridge
