## Environment REDIS
version: '3.8'
services:

  ##################### REDIS #####################
  environment-redis:
    container_name: environment-redis
    image: redis:7.0-rc1-alpine3.15
    labels:
      environment-redis: "environment-redis"
    volumes:
      - ./data:/data
    env_file:
      - ./.env
    environment:
      REDIS_PASSWORD: Alterar123
    command: redis-server --save 20 1 --loglevel warning --requirepass Alterar123
    networks:
      environment-redis:
    restart: always
    ports:
      - 6379:6379 # host:container

##################### VOLUMES #####################
volumes:
  environment-redis:
    name: environment-redis

##################### NETWORKS #####################
networks:
  environment-redis:
    name: environment-redis
    driver: bridge
