## Environment SGDB
version: '3.8'

services:

  ##################### MYSQL #####################
  environment-mysql:
    profiles: [ "all", "mysql" ]
    extends:
      file: ./sgdb-mysql/docker-compose.yml
      service: environment-mysql

  ##################### POSTGRES #####################
  environment-postgres:
    profiles: [ "all", "postgres" ]
    extends:
      file: ./sgdb-postgres/docker-compose.yml
      service: environment-postgres

  ##################### DYNAMODB #####################
  environment-dynamodb:
    profiles: [ "all", "dynamodb" ]
    extends:
      file: ./sgdb-dynamodb/docker-compose.yml
      service: environment-dynamodb

  ##################### ELASTICSEARCH #####################
  environment-elasticsearch:
    profiles: [ "all", "elasticsearch" ]
    extends:
      file: ./sgdb-elasticsearch/docker-compose.yml
      service: environment-elasticsearch

  ##################### MONGODB #####################
  environment-mongodb:
    profiles: [ "all", "mongodb" ]
    extends:
      file: ./sgdb-mongodb/docker-compose.yml
      service: environment-mongodb

  ##################### REDIS #####################
  environment-redis:
    profiles: [ "all", "redis" ]
    extends:
      file: ./sgdb-redis/docker-compose.yml
      service: environment-redis

##################### VOLUMES #####################
volumes:
  environment-mysql:
    name: environment-mysql
  environment-postgres:
    name: environment-postgres
  environment-dynamodb:
    name: environment-dynamodb
  environment-elasticsearch:
    name: environment-elasticsearch
  environment-mongodb:
    name: environment-mongodb
  environment-redis:
    name: environment-redis

##################### NETWORKS #####################
networks:
  environment-mysql:
    name: environment-mysql
  environment-postgres:
    name: environment-postgres
  environment-dynamodb:
    name: environment-dynamodb
  environment-elasticsearch:
    name: environment-elasticsearch
  environment-mongodb:
    name: environment-mongodb
  environment-redis:
    name: environment-redis
