name: Workflow - Push em Dockerhub

on:
  push:
    branches:
      - 'main'
env:
  IMAGE_NAME: go-environment

jobs:      
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
      -
        name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ‘1.18.3’
      - 
        name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - 
        name: Run build
        run: go build .

      - name: Run vet & lint
        run: |
          go vet .
          golint .
      - 
        name: Run testing
        run: cd test && go test -v
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest
